#!/bin/sh

# dmarc-parser
# A wrapper script for invoking dmarc-parser with docker
# Put this script in $PATH as `dmarcparse`

PROGNAME="$(basename $0)"
VERSION="0.0.3"

# Helper functions for guards
error(){
  error_code=$1
  echo "ERROR: $2" >&2
  echo "($PROGNAME wrapper version: $VERSION, error code: $error_code )" &>2
  exit $1
}

check_cmd_in_path(){
  cmd=$1
  which $cmd > /dev/null 2>&1 || error 1 "$cmd not found!"
}

# Guards (checks for dependencies)
check_cmd_in_path docker

# Set up mounted volumes, environment, and run our containerized command
exec docker run \
  --interactive --tty --rm \
  --volume "/etc/dmarcts/dmarcts-report-parser.conf":/usr/local/bin/dmarcts-report-parser.conf \
  --workdir /usr/local/bin \
  "dmarcparse:$VERSION" "$@"
